- after migration, auto add initial test data for testing validation...done - fixed primary key not being set
```ts
MissingPrimaryColumnError: Entity "CdAiUsageLogsTypeModel" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.
```

- implement views

- set up GenEntityController.RegisterModuleInCdInstance() as a task
- before starting tests
  - register cd-ai as a module (The module cd-ai is not registered in this corpdesk instance)
- create post execution functon to handle printing of result summary
- purge module (cd-api)
  - deregister module
  - purge module from db

- manual tests for all the modules and methods
  - create
  - read
  - update
  - delete

- remove .mustExist("userId", CdAiModel) from cd-ai-service

- initial test data should be automated and reported
  - The test should include internal and http crud tests

- EntityPropertyNotFoundError: Property "cdAiTypeGuid" was not found in "CdAiViewModel"
  - make sure cd_ai_type_guid is part of the view at the db
  - make sure cd_ai_type_guid is part of auto construction of view during migration.
  - make sure cdAiTypeGuid is a property of entity in the CdAiViewModel
  - make sure cd_ai_type_guid is part of view statement in the CdAiViewModel